[package]
name = "grid"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29.2", optional = true }
serde = { version = "1.0.216", features = ["derive"], optional = true }

[features]
glam = ["dep:glam"]
serde = ["dep:serde"]